language: python
python:
  - 2.7 # EOL in 2020
  - 3.6
  - 3.7

addons:
  apt:
    packages:
    - python-dev
    - python3-dev

install:
  - if [ $(python -c 'import sys; print(sys.version_info[0])') = "3" ]; then pip install --upgrade 'importlib-metadata > 4'; fi
  - python setup.py install

before_script:
  # Clone public samples
  - git clone https://github.com/theopolis/uefi-firmware-samples samples

script:
  # Run the unittests
  - python -bb ./tests/test_compression.py

  # Run a test script against all samples
  - (cd samples && python -bb ./test_samples.py)
